/** ISO 4217 active currencies (alphabetical by code). */
export const CURRENCIES = [
  { code: 'AED', label: 'UAE Dirham (AED)' },
  { code: 'AFN', label: 'Afghan Afghani (AFN)' },
  { code: 'ALL', label: 'Albanian Lek (ALL)' },
  { code: 'AMD', label: 'Armenian Dram (AMD)' },
  { code: 'ANG', label: 'Netherlands Antillean Guilder (ANG)' },
  { code: 'AOA', label: 'Angolan Kwanza (AOA)' },
  { code: 'ARS', label: 'Argentine Peso (ARS)' },
  { code: 'AUD', label: 'Australian Dollar (AUD)' },
  { code: 'AWG', label: 'Aruban Florin (AWG)' },
  { code: 'AZN', label: 'Azerbaijani Manat (AZN)' },
  { code: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark (BAM)' },
  { code: 'BBD', label: 'Barbadian Dollar (BBD)' },
  { code: 'BDT', label: 'Bangladeshi Taka (BDT)' },
  { code: 'BGN', label: 'Bulgarian Lev (BGN)' },
  { code: 'BHD', label: 'Bahraini Dinar (BHD)' },
  { code: 'BIF', label: 'Burundian Franc (BIF)' },
  { code: 'BMD', label: 'Bermudan Dollar (BMD)' },
  { code: 'BND', label: 'Brunei Dollar (BND)' },
  { code: 'BOB', label: 'Bolivian Boliviano (BOB)' },
  { code: 'BRL', label: 'Brazilian Real (BRL)' },
  { code: 'BSD', label: 'Bahamian Dollar (BSD)' },
  { code: 'BTN', label: 'Bhutanese Ngultrum (BTN)' },
  { code: 'BWP', label: 'Botswanan Pula (BWP)' },
  { code: 'BYN', label: 'Belarusian Ruble (BYN)' },
  { code: 'BZD', label: 'Belize Dollar (BZD)' },
  { code: 'CAD', label: 'Canadian Dollar (CAD)' },
  { code: 'CDF', label: 'Congolese Franc (CDF)' },
  { code: 'CHF', label: 'Swiss Franc (CHF)' },
  { code: 'CLP', label: 'Chilean Peso (CLP)' },
  { code: 'CNY', label: 'Chinese Yuan (CNY)' },
  { code: 'COP', label: 'Colombian Peso (COP)' },
  { code: 'CRC', label: 'Costa Rican Colón (CRC)' },
  { code: 'CUP', label: 'Cuban Peso (CUP)' },
  { code: 'CVE', label: 'Cape Verdean Escudo (CVE)' },
  { code: 'CZK', label: 'Czech Koruna (CZK)' },
  { code: 'DJF', label: 'Djiboutian Franc (DJF)' },
  { code: 'DKK', label: 'Danish Krone (DKK)' },
  { code: 'DOP', label: 'Dominican Peso (DOP)' },
  { code: 'DZD', label: 'Algerian Dinar (DZD)' },
  { code: 'EGP', label: 'Egyptian Pound (EGP)' },
  { code: 'ERN', label: 'Eritrean Nakfa (ERN)' },
  { code: 'ETB', label: 'Ethiopian Birr (ETB)' },
  { code: 'EUR', label: 'Euro (EUR)' },
  { code: 'FJD', label: 'Fijian Dollar (FJD)' },
  { code: 'FKP', label: 'Falkland Islands Pound (FKP)' },
  { code: 'GBP', label: 'British Pound (GBP)' },
  { code: 'GEL', label: 'Georgian Lari (GEL)' },
  { code: 'GHS', label: 'Ghanaian Cedi (GHS)' },
  { code: 'GIP', label: 'Gibraltar Pound (GIP)' },
  { code: 'GMD', label: 'Gambian Dalasi (GMD)' },
  { code: 'GNF', label: 'Guinean Franc (GNF)' },
  { code: 'GTQ', label: 'Guatemalan Quetzal (GTQ)' },
  { code: 'GYD', label: 'Guyanaese Dollar (GYD)' },
  { code: 'HKD', label: 'Hong Kong Dollar (HKD)' },
  { code: 'HNL', label: 'Honduran Lempira (HNL)' },
  { code: 'HTG', label: 'Haitian Gourde (HTG)' },
  { code: 'HUF', label: 'Hungarian Forint (HUF)' },
  { code: 'IDR', label: 'Indonesian Rupiah (IDR)' },
  { code: 'ILS', label: 'Israeli New Shekel (ILS)' },
  { code: 'INR', label: 'Indian Rupee (INR)' },
  { code: 'IQD', label: 'Iraqi Dinar (IQD)' },
  { code: 'IRR', label: 'Iranian Rial (IRR)' },
  { code: 'ISK', label: 'Icelandic Króna (ISK)' },
  { code: 'JMD', label: 'Jamaican Dollar (JMD)' },
  { code: 'JOD', label: 'Jordanian Dinar (JOD)' },
  { code: 'JPY', label: 'Japanese Yen (JPY)' },
  { code: 'KES', label: 'Kenyan Shilling (KES)' },
  { code: 'KGS', label: 'Kyrgystani Som (KGS)' },
  { code: 'KHR', label: 'Cambodian Riel (KHR)' },
  { code: 'KMF', label: 'Comorian Franc (KMF)' },
  { code: 'KPW', label: 'North Korean Won (KPW)' },
  { code: 'KRW', label: 'South Korean Won (KRW)' },
  { code: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
  { code: 'KYD', label: 'Cayman Islands Dollar (KYD)' },
  { code: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
  { code: 'LAK', label: 'Laotian Kip (LAK)' },
  { code: 'LBP', label: 'Lebanese Pound (LBP)' },
  { code: 'LKR', label: 'Sri Lankan Rupee (LKR)' },
  { code: 'LRD', label: 'Liberian Dollar (LRD)' },
  { code: 'LSL', label: 'Lesotho Loti (LSL)' },
  { code: 'LYD', label: 'Libyan Dinar (LYD)' },
  { code: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { code: 'MDL', label: 'Moldovan Leu (MDL)' },
  { code: 'MGA', label: 'Malagasy Ariary (MGA)' },
  { code: 'MKD', label: 'Macedonian Denar (MKD)' },
  { code: 'MMK', label: 'Myanmar Kyat (MMK)' },
  { code: 'MNT', label: 'Mongolian Tugrik (MNT)' },
  { code: 'MOP', label: 'Macanese Pataca (MOP)' },
  { code: 'MRU', label: 'Mauritanian Ouguiya (MRU)' },
  { code: 'MUR', label: 'Mauritian Rupee (MUR)' },
  { code: 'MVR', label: 'Maldivian Rufiyaa (MVR)' },
  { code: 'MWK', label: 'Malawian Kwacha (MWK)' },
  { code: 'MXN', label: 'Mexican Peso (MXN)' },
  { code: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { code: 'MZN', label: 'Mozambican Metical (MZN)' },
  { code: 'NAD', label: 'Namibian Dollar (NAD)' },
  { code: 'NGN', label: 'Nigerian Naira (NGN)' },
  { code: 'NIO', label: 'Nicaraguan Córdoba (NIO)' },
  { code: 'NOK', label: 'Norwegian Krone (NOK)' },
  { code: 'NPR', label: 'Nepalese Rupee (NPR)' },
  { code: 'NZD', label: 'New Zealand Dollar (NZD)' },
  { code: 'OMR', label: 'Omani Rial (OMR)' },
  { code: 'PAB', label: 'Panamanian Balboa (PAB)' },
  { code: 'PEN', label: 'Peruvian Sol (PEN)' },
  { code: 'PGK', label: 'Papua New Guinean Kina (PGK)' },
  { code: 'PHP', label: 'Philippine Peso (PHP)' },
  { code: 'PKR', label: 'Pakistani Rupee (PKR)' },
  { code: 'PLN', label: 'Polish Złoty (PLN)' },
  { code: 'PYG', label: 'Paraguayan Guarani (PYG)' },
  { code: 'QAR', label: 'Qatari Riyal (QAR)' },
  { code: 'RON', label: 'Romanian Leu (RON)' },
  { code: 'RSD', label: 'Serbian Dinar (RSD)' },
  { code: 'RUB', label: 'Russian Ruble (RUB)' },
  { code: 'RWF', label: 'Rwandan Franc (RWF)' },
  { code: 'SAR', label: 'Saudi Riyal (SAR)' },
  { code: 'SBD', label: 'Solomon Islands Dollar (SBD)' },
  { code: 'SCR', label: 'Seychellois Rupee (SCR)' },
  { code: 'SDG', label: 'Sudanese Pound (SDG)' },
  { code: 'SEK', label: 'Swedish Krona (SEK)' },
  { code: 'SGD', label: 'Singapore Dollar (SGD)' },
  { code: 'SHP', label: 'Saint Helena Pound (SHP)' },
  { code: 'SLE', label: 'Sierra Leonean Leone (SLE)' },
  { code: 'SOS', label: 'Somali Shilling (SOS)' },
  { code: 'SRD', label: 'Surinamese Dollar (SRD)' },
  { code: 'SSP', label: 'South Sudanese Pound (SSP)' },
  { code: 'STN', label: 'São Tomé and Príncipe Dobra (STN)' },
  { code: 'SYP', label: 'Syrian Pound (SYP)' },
  { code: 'SZL', label: 'Swazi Lilangeni (SZL)' },
  { code: 'THB', label: 'Thai Baht (THB)' },
  { code: 'TJS', label: 'Tajikistani Somoni (TJS)' },
  { code: 'TMT', label: 'Turkmenistani Manat (TMT)' },
  { code: 'TND', label: 'Tunisian Dinar (TND)' },
  { code: 'TOP', label: 'Tongan Paʻanga (TOP)' },
  { code: 'TRY', label: 'Turkish Lira (TRY)' },
  { code: 'TTD', label: 'Trinidad and Tobago Dollar (TTD)' },
  { code: 'TWD', label: 'New Taiwan Dollar (TWD)' },
  { code: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { code: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
  { code: 'UGX', label: 'Ugandan Shilling (UGX)' },
  { code: 'USD', label: 'US Dollar (USD)' },
  { code: 'UYU', label: 'Uruguayan Peso (UYU)' },
  { code: 'UZS', label: 'Uzbekistani Som (UZS)' },
  { code: 'VES', label: 'Venezuelan Bolívar (VES)' },
  { code: 'VND', label: 'Vietnamese Đồng (VND)' },
  { code: 'VUV', label: 'Vanuatu Vatu (VUV)' },
  { code: 'WST', label: 'Samoan Tala (WST)' },
  { code: 'XAF', label: 'Central African CFA Franc (XAF)' },
  { code: 'XCD', label: 'East Caribbean Dollar (XCD)' },
  { code: 'XOF', label: 'West African CFA Franc (XOF)' },
  { code: 'XPF', label: 'CFP Franc (XPF)' },
  { code: 'YER', label: 'Yemeni Rial (YER)' },
  { code: 'ZAR', label: 'South African Rand (ZAR)' },
  { code: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
  { code: 'ZWL', label: 'Zimbabwean Dollar (ZWL)' },
] as const;

export type CurrencyCode = string;

export const DEFAULT_CURRENCY = 'USD';

/** Display-only formatter. Never compute money totals on the client. */
export function formatMoney(n: number, currency: string = DEFAULT_CURRENCY) {
  try {
    return n.toLocaleString(undefined, {
      style: 'currency',
      currency,
    });
  } catch {
    return n.toLocaleString(undefined, {
      style: 'currency',
      currency: DEFAULT_CURRENCY,
    });
  }
}
